micronaut:
  application:
    name: casaDoCodigo
datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/cdc?createDatabaseIfNotExist=true`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:`root`}
    password: ${DB_PASSWORD:`root`}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
